default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webapi_development
  username: postgres
  password:

test:
  <<: *default
  database: webapi_test
  username: postgres
  password:

staging:
  <<: *default
  host: production.caazdhmsksck.eu-central-1.rds.amazonaws.com
  database: webapistaging
  username: webapistaginguser
  password: <%= Rails.application.credentials.dig(:db, :staging_password) %>

production:
  host: production.caazdhmsksck.eu-central-1.rds.amazonaws.com
  <<: *default
  database: webapiproduction
  username: webapiproductionuser
  password: <%= Rails.application.credentials.dig(:db, :production_password) %>
