name: Deploy to AWS ECS Fargate (Staging)

on:
  push:
    branches:
      - 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t 837134151110.dkr.ecr.eu-central-1.amazonaws.com/webapi:staging .

      - name: Log into ECR
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 837134151110.dkr.ecr.eu-central-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Push image
        run: docker push 837134151110.dkr.ecr.eu-central-1.amazonaws.com/webapi:staging

      - name: Force new deployment
        run: aws ecs update-service --cluster webapi-cluster --service webapi-web-staging --force-new-deployment --region eu-central-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# aws ecr get-login-password | docker login --username AWS --password-stdin 837134151110.dkr.ecr.eu-central-1.amazonaws.com
